### ISSUE TITLE
Command createVsCmdPrompt not found

### ISSUE THREAD

**Issue by Subtixx** [espresso3389/vcterminal-vscode#1]
> command 'terminalVcVers.createVsCmdPrompt' not found

Installed in through the Extensions Tab (Ctrl+Shift+X), reloaded the editor, edited my settings.json (because it defaults to powershell in my case), and tried opening the vscmdprompt.

Version:

> Version 1.9.1
> Commit f9d0c687ff2ea7aabd85fb9a43129117c0ecf519
> Date 2017-02-09T00:26:45.394Z
> Shell 1.4.6
> Renderer 53.0.2785.143
> Node 6.5.0

**Comment by espresso3389** [comment]
On my machine, it works correctly on 1.9.1 and 1.10.0-insider.
I have no idea why the extension failed to run.

Could you please reinstall (Uninstall and Install) the extension?

**Comment by Subtixx** [comment]
Hm. Weird. After I uninstalled the extension, restarted the whole application, installed, and restarted the whole application again it worked.. Before I tried it with reload window which didn't work.

Maybe it had something to do that I edited the settings.json AFTER installing your extension?

btw: Thanks for the fast response. You're awesome :)

**Comment by espresso3389** [comment]
I want t o explain about the root cause of the issue.
VSCode recently (in these two months) changed the default terminal to powershell and it breaks internal consistency of vcterminal-vscode. Of course, if you explicitly change `terminal.integrated.shell.windows` value to something like `C:\\WINDOWS\\Sysnative\\cmd.exe` (it's my case).

I've updated the code to deal with cmd.exe and powershell.exe installed on either system32 or sysnative directory. I think it resolves the issue completely.

**Comment by Subtixx** [comment]
Thank you for reporting back! Great that you figured out what is causing the issue and thanks for fixing it so fast. :)
